#!/bin/bash

NEPER="neper --rcfile none"

# # $NEPER -T -n from_morpho -morpho "diameq:lognormal(0.1,0.03),1-sphericity:lognormal(0.145,0.03),aspratio(2,1,0.5)" -group "id<=500?1:2" -o gene_grou_1

# # $NEPER -T -n from_morpho -morpho "diameq:lognormal(0.1,0.03),1-sphericity:lognormal(0.145,0.03)" -group "id<=500?1:2" -o gene_grou_1 -regularization 1 -statcell diameq,sphericity

# # $NEPER -T -n 1000 -group "id<=500?1:2" -o gene_grou_1
# # $NEPER -T -n 1000 -group "vol>=0.001?1:2" -o gene_grou_2
$NEPER -T -n 1000 -domain "cube(2,1,1)" -morpho "diameq:0.5*lognormal(1,0.35)+0.5*lognormal(2,0.6),1-sphericity:lognormal(0.6,0.03)" -group mode -o gene_grou_3  -regularization 1 -statcell diameq,sphericity # separated by mode (most frequent value in statistics)

# neper -V gene_grou_3.tess -print img_of_tess

# C="-datacellcol group -datacelltrs 0.5 -cameraangle 12 -imagesize 600:600"
# $NEPER -V gene_grou_1.tess $C -print gene_grou_1
# $NEPER -V gene_grou_2.tess $C -print gene_grou_2
$NEPER -V gene_grou_3.tess $C -print gene_grou_3

$NEPER -M  gene_grou_3.tess -order 1 -rcl 0.5 

neper -V gene_grou_3.msh -print img_of_mesh

convert +append gene_grou_?.png gene_grou.png

exit 0