version: '3'

services:
  meshing:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '24G'

